title: "Noda Laboratory | Kochi University of Technology"
description: "Ubiquitous Imperceptible Electronics Laboratory"
lang: ja
timezone: Asia/Tokyo

# GitHub Pages settings
# If you publish at https://username.github.io/lab-website-template/,
# set baseurl: "/lab-website-template"
# If you publish at https://username.github.io/,
# set baseurl: ""
baseurl: "/lab-website"
url: "https://akihito-noda.github.io/lab-website/"

# Build settings
markdown: kramdown
permalink: /news/:year/:month/:day/:title/

# Site navigation
nav:
  - title: "Home"
    url: "/"
  - title: "Research"
    url: "/research/"
  - title: "Members"
    url: "/members/"
  - title: "Publications"
    url: "/publications/"
  - title: News
    url: /news/
  - title: "For Students"
    url: "/for-students/"
  - title: "Access"
    url: "/access/"

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
